# cval config
[cval]
embed_model = "openai"
inference_model = "gpt-4o-2024-05-13" #"llama3:70b"
with_rag = true

# ingestions
splitting = "sentence" # "sentence", "token", "semantic", "recursive"
extractors = [] # ["summary", "keyword", title]
num_websites = 5

# retrieval
temperature = 0.0
num_queries = 3
top_k = 5
alpha = 1   #weight for sparse/dense retrieval, only used for hybrid query mode.
rerank = "sentence" # "sentence" or "llm"
top_n = 3
with_rewriting = true

# data
[data]
urls = [        
    "https://maven.apache.org/pom.html",
    "https://maven.apache.org/ref/3.9.7/maven-model/maven.html",
    "https://maven.apache.org/ref/3.9.7/maven-settings/settings.html",
    "https://maven.apache.org/ref/3.9.7/maven-core/toolchains.html",
    "https://maven.apache.org/guides/getting-started/index.html",
    "https://docs.spring.io/spring-boot/appendix/application-properties/index.html",
    "https://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/html/howto-properties-and-configuration.html",
    "https://docs.spring.io/spring-boot/reference/features/external-config.html",
    "https://docs.spring.io/spring-boot/reference/features/profiles.html",
    "https://docs.docker.com/compose/compose-file/",
    "https://docs.docker.com/compose/compose-application-model/",
    "https://docs.docker.com/compose/intro/features-uses/",
    "https://docs.docker.com/compose/gettingstarted/",
    "https://docs.docker.com/compose/compose-file/04-version-and-name/",
    "https://docs.docker.com/compose/compose-file/05-services/",
    "https://docs.docker.com/compose/compose-file/06-networks/",
    "https://docs.docker.com/compose/compose-file/07-volumes/",
    "https://docs.docker.com/compose/compose-file/08-configs/",
    "https://docs.docker.com/compose/compose-file/09-secrets/",
    "https://docs.docker.com/compose/compose-file/10-fragments/",
    "https://docs.docker.com/compose/compose-file/11-extension/",
    "https://docs.docker.com/compose/compose-file/12-interpolation/",
    "https://docs.docker.com/compose/compose-file/13-merge/",
    "https://docs.docker.com/compose/compose-file/14-include/",
    "https://docs.docker.com/compose/compose-file/15-profiles/",
    "https://docs.docker.com/compose/compose-file/build/",
    "https://docs.docker.com/compose/compose-file/deploy/",
    "https://docs.docker.com/compose/compose-file/develop/",
    "https://docs.docker.com/reference/dockerfile/",
    "https://docs.docker.com/build/building/packaging/",
    "https://docs.docker.com/build/building/multi-stage/"
]
github = [
    "macrozheng/mall",
    "apolloconfig/apollo",
    "linlinjava/litemall",
    "sqshq/piggymetrics",
    "codecentric/spring-boot-admin",
    "macrozheng/mall-swarm",
    "wxiaoqi/Spring-Cloud-Platform",
    "pig-mesh/pig",
    "jetlinks/jetlinks-community",
    "Yin-Hongwei/music-website"
]
data_dir = "../data/so_posts"


