index:
  tech-docs:
    type: "url"
    path: "../data/tech_docs.json"
    dimension: 1536
    metric: "cosine"
    splitting: "sentence"
  so-posts:
    type: "dir"
    path: "../data/so_posts/"
    dimension: 1536
    metric: "cosine"
    splitting: "sentence"
  