# general
data_file = "../data/results/test.json"
output_file = "../data/results/test_gpt-3.5-turbo-0125.json"
with_rag = true
with_refinements = true
model_name = "gpt-3.5-turbo-0125" #["gpt-3.5-turbo-0125", "gpt-4o-2024-05-13", "llama3:70b", "llama3:8b"]
temperature = 0.0