# general
data_file = "../data/results/config2/all_dependencies_all_gpt-3.5-turbo-0125.json"
output_dir = "../data/results/config2"
with_rag = true
index_name = "all"
tool_name = "cfgnet"
model_name = "gpt-3.5-turbo-0125" #["gpt-3.5-turbo-0125", "gpt-4o-2024-05-13", "llama3:70b", "llama3:8b"]
temperature = 0.0