# general
data_file = "../data/evaluation/config2/all_dependencies_all.json"
index_name = "all"
tool_name = "cfgnet"
model_name = "llama3:70b" #["gpt-3.5-turbo-0125", "gpt-4o-2024-05-13", "llama3:70b", "llama3:8b"]
temperature = 0.0