index_name = "ada-index"
embedding_model = "openai"
embedding_dimension = 1536
rerank = "sentence"
top_n = 5
num_websites = 3
top_k = 10
alpha = 0.5
web_search_enabled = true
inference_models = [
    "gpt-4o-mini-2024-07-18",
    "gpt-4o-2024-11-20",
    "deepseek-r1:14b",
    "llama3.1:70b",
    "deepseek-r1:70b",
    "llama3.1:8b",
]
temperature = 0.5
with_context = true
data_file = "data/evaluation/test_dependencies.csv"
retrieval_file = "data/evaluation/retrieval_results/test_dependencies_advanced1.json"
generation_file = "data/evaluation/generation_results/test_dependencies_advanced1.json"
advanced = true

