embedding_model = "openai"
inference_models = [
    "gpt-4o-mini-2024-07-18",
    "gpt-4o-2024-11-20",
    "deepseek-r1:14b",
    "deepseek-r1:70b",
    "llama3.1:70b",
    "llama3.1:8b",
]
temperature = 0.5
with_context = false
data_file = "data/evaluation/all_dependencies.csv"
retrieval_file = "data/evaluation/retrieval_results/all_dependencies_config0.json"
generation_file = "data/evaluation/generation_results/all_dependencies_config0.json"
advanced = false