index_name = "qwen-index"
embedding_model = "qwen"
embedding_dimension = 3584
rerank = "sentence"
top_n = 3
inference_model = [
    "gpt-4o-mini-2024-07-18",
    "gpt-4o-2024-11-20",
    "deepseek-r1:14b",
    "deepseek-r1:70b",
    "llama3:70b",
    "phi4:latest"
]
temperature = 0.5
with_rag = true
data_file = "data/evaluation/test_dependencies.csv"