inference_models = [
    "gpt-4o-mini-2024-07-18",
    "gpt-4o-2024-11-20",
    "deepseek-r1:14b",
    "llama3.1:70b",
    "deepseek-r1:70b",
    "llama3.1:8b",
]
temperature = [0.0] #[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
with_context = true
data_file = "data/evaluation/sensitivity/test_dependencies_advanced1_sampled.json"
advanced = true